default[:resque][:exec_prefix] = "exec"
default[:resque][:environment] = "production"
default[:resque][:config_file] = "config/resque.yml"
default[:resque][:pids_dir] = "tmp/pids"
default[:resque][:resque_conf] = "/etc/resque.conf"
default[:resque][:user] = "root"
